// Generated by Wrangler by running `wrangler types`

interface Env {
	CONVERSATION_KV: KVNamespace;
	ENVIRONMENT: "development";
	RELAY_URL: "https://relay.firela.io";
	DB: D1Database;
	VECTORIZE: VectorizeIndex;
}
